import { PokemonTypes, type Pokemon } from "~/components/pokemon/PokemonTypes";

export const pokemon_gen4: Array<Pokemon> = [
  { name: "Bulbasaur", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Ivysaur", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Venusaur", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Charmander", type: [PokemonTypes.fire] },
  { name: "Charmeleon", type: [PokemonTypes.fire] },
  { name: "Charizard", type: [PokemonTypes.fire, PokemonTypes.flying] },
  { name: "Squirtle", type: [PokemonTypes.water] },
  { name: "Wartortle", type: [PokemonTypes.water] },
  { name: "Blastoise", type: [PokemonTypes.water] },
  { name: "Caterpie", type: [PokemonTypes.bug] },
  { name: "Metapod", type: [PokemonTypes.bug] },
  { name: "Butterfree", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Weedle", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Kakuna", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Beedrill", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Pidgey", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Pidgeotto", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Pidgeot", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Rattata", type: [PokemonTypes.normal] },
  { name: "Raticate", type: [PokemonTypes.normal] },
  { name: "Spearow", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Fearow", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Ekans", type: [PokemonTypes.poison] },
  { name: "Arbok", type: [PokemonTypes.poison] },
  { name: "Pikachu", type: [PokemonTypes.electric] },
  { name: "Raichu", type: [PokemonTypes.electric] },
  { name: "Sandshrew", type: [PokemonTypes.ground] },
  { name: "Sandslash", type: [PokemonTypes.ground] },
  { name: "Nidoran♀", type: [PokemonTypes.poison] },
  { name: "Nidorina", type: [PokemonTypes.poison] },
  { name: "Nidoqueen", type: [PokemonTypes.poison, PokemonTypes.ground] },
  { name: "Nidoran♂", type: [PokemonTypes.poison] },
  { name: "Nidorino", type: [PokemonTypes.poison] },
  { name: "Nidoking", type: [PokemonTypes.poison, PokemonTypes.ground] },
  { name: "Clefairy", type: [PokemonTypes.normal] },
  { name: "Clefable", type: [PokemonTypes.normal] },
  { name: "Vulpix", type: [PokemonTypes.fire] },
  { name: "Ninetales", type: [PokemonTypes.fire] },
  { name: "Jigglypuff", type: [PokemonTypes.normal] },
  { name: "Wigglytuff", type: [PokemonTypes.normal] },
  { name: "Zubat", type: [PokemonTypes.poison, PokemonTypes.flying] },
  { name: "Golbat", type: [PokemonTypes.poison, PokemonTypes.flying] },
  { name: "Oddish", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Gloom", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Vileplume", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Paras", type: [PokemonTypes.bug, PokemonTypes.grass] },
  { name: "Parasect", type: [PokemonTypes.bug, PokemonTypes.grass] },
  { name: "Venonat", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Venomoth", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Diglett", type: [PokemonTypes.ground] },
  { name: "Dugtrio", type: [PokemonTypes.ground] },
  { name: "Meowth", type: [PokemonTypes.normal] },
  { name: "Persian", type: [PokemonTypes.normal] },
  { name: "Psyduck", type: [PokemonTypes.water] },
  { name: "Golduck", type: [PokemonTypes.water] },
  { name: "Mankey", type: [PokemonTypes.fighting] },
  { name: "Primeape", type: [PokemonTypes.fighting] },
  { name: "Growlithe", type: [PokemonTypes.fire] },
  { name: "Arcanine", type: [PokemonTypes.fire] },
  { name: "Poliwag", type: [PokemonTypes.water] },
  { name: "Poliwhirl", type: [PokemonTypes.water] },
  { name: "Poliwrath", type: [PokemonTypes.water, PokemonTypes.fighting] },
  { name: "Abra", type: [PokemonTypes.psychic] },
  { name: "Kadabra", type: [PokemonTypes.psychic] },
  { name: "Alakazam", type: [PokemonTypes.psychic] },
  { name: "Machop", type: [PokemonTypes.fighting] },
  { name: "Machoke", type: [PokemonTypes.fighting] },
  { name: "Machamp", type: [PokemonTypes.fighting] },
  { name: "Bellsprout", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Weepinbell", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Victreebel", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Tentacool", type: [PokemonTypes.water, PokemonTypes.poison] },
  { name: "Tentacruel", type: [PokemonTypes.water, PokemonTypes.poison] },
  { name: "Geodude", type: [PokemonTypes.rock, PokemonTypes.ground] },
  { name: "Graveler", type: [PokemonTypes.rock, PokemonTypes.ground] },
  { name: "Golem", type: [PokemonTypes.rock, PokemonTypes.ground] },
  { name: "Ponyta", type: [PokemonTypes.fire] },
  { name: "Rapidash", type: [PokemonTypes.fire] },
  { name: "Slowpoke", type: [PokemonTypes.water, PokemonTypes.psychic] },
  { name: "Slowbro", type: [PokemonTypes.water, PokemonTypes.psychic] },
  { name: "Magnemite", type: [PokemonTypes.electric, PokemonTypes.steel] },
  { name: "Magneton", type: [PokemonTypes.electric, PokemonTypes.steel] },
  { name: "Farfetch'd", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Doduo", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Dodrio", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Seel", type: [PokemonTypes.water] },
  { name: "Dewgong", type: [PokemonTypes.water, PokemonTypes.ice] },
  { name: "Grimer", type: [PokemonTypes.poison] },
  { name: "Muk", type: [PokemonTypes.poison] },
  { name: "Shellder", type: [PokemonTypes.water] },
  { name: "Cloyster", type: [PokemonTypes.water, PokemonTypes.ice] },
  { name: "Gastly", type: [PokemonTypes.ghost, PokemonTypes.poison] },
  { name: "Haunter", type: [PokemonTypes.ghost, PokemonTypes.poison] },
  { name: "Gengar", type: [PokemonTypes.ghost, PokemonTypes.poison] },
  { name: "Onix", type: [PokemonTypes.rock, PokemonTypes.ground] },
  { name: "Drowzee", type: [PokemonTypes.psychic] },
  { name: "Hypno", type: [PokemonTypes.psychic] },
  { name: "Krabby", type: [PokemonTypes.water] },
  { name: "Kingler", type: [PokemonTypes.water] },
  { name: "Voltorb", type: [PokemonTypes.electric] },
  { name: "Electrode", type: [PokemonTypes.electric] },
  { name: "Exeggcute", type: [PokemonTypes.grass, PokemonTypes.psychic] },
  { name: "Exeggutor", type: [PokemonTypes.grass, PokemonTypes.psychic] },
  { name: "Cubone", type: [PokemonTypes.ground] },
  { name: "Marowak", type: [PokemonTypes.ground] },
  { name: "Hitmonlee", type: [PokemonTypes.fighting] },
  { name: "Hitmonchan", type: [PokemonTypes.fighting] },
  { name: "Lickitung", type: [PokemonTypes.normal] },
  { name: "Koffing", type: [PokemonTypes.poison] },
  { name: "Weezing", type: [PokemonTypes.poison] },
  { name: "Rhyhorn", type: [PokemonTypes.ground, PokemonTypes.rock] },
  { name: "Rhydon", type: [PokemonTypes.ground, PokemonTypes.rock] },
  { name: "Chansey", type: [PokemonTypes.normal] },
  { name: "Tangela", type: [PokemonTypes.grass] },
  { name: "Kangaskhan", type: [PokemonTypes.normal] },
  { name: "Horsea", type: [PokemonTypes.water] },
  { name: "Seadra", type: [PokemonTypes.water] },
  { name: "Goldeen", type: [PokemonTypes.water] },
  { name: "Seaking", type: [PokemonTypes.water] },
  { name: "Staryu", type: [PokemonTypes.water] },
  { name: "Starmie", type: [PokemonTypes.water, PokemonTypes.psychic] },
  { name: "Mr. Mime", type: [PokemonTypes.psychic] },
  { name: "Scyther", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Jynx", type: [PokemonTypes.ice, PokemonTypes.psychic] },
  { name: "Electabuzz", type: [PokemonTypes.electric] },
  { name: "Magmar", type: [PokemonTypes.fire] },
  { name: "Pinsir", type: [PokemonTypes.bug] },
  { name: "Tauros", type: [PokemonTypes.normal] },
  { name: "Magikarp", type: [PokemonTypes.water] },
  { name: "Gyarados", type: [PokemonTypes.water, PokemonTypes.flying] },
  { name: "Lapras", type: [PokemonTypes.water, PokemonTypes.ice] },
  { name: "Ditto", type: [PokemonTypes.normal] },
  { name: "Eevee", type: [PokemonTypes.normal] },
  { name: "Vaporeon", type: [PokemonTypes.water] },
  { name: "Jolteon", type: [PokemonTypes.electric] },
  { name: "Flareon", type: [PokemonTypes.fire] },
  { name: "Porygon", type: [PokemonTypes.normal] },
  { name: "Omanyte", type: [PokemonTypes.rock, PokemonTypes.water] },
  { name: "Omastar", type: [PokemonTypes.rock, PokemonTypes.water] },
  { name: "Kabuto", type: [PokemonTypes.rock, PokemonTypes.water] },
  { name: "Kabutops", type: [PokemonTypes.rock, PokemonTypes.water] },
  { name: "Aerodactyl", type: [PokemonTypes.rock, PokemonTypes.flying] },
  { name: "Snorlax", type: [PokemonTypes.normal] },
  { name: "Articuno", type: [PokemonTypes.ice, PokemonTypes.flying] },
  { name: "Zapdos", type: [PokemonTypes.electric, PokemonTypes.flying] },
  { name: "Moltres", type: [PokemonTypes.fire, PokemonTypes.flying] },
  { name: "Dratini", type: [PokemonTypes.dragon] },
  { name: "Dragonair", type: [PokemonTypes.dragon] },
  { name: "Dragonite", type: [PokemonTypes.dragon, PokemonTypes.flying] },
  { name: "Mewtwo", type: [PokemonTypes.psychic] },
  { name: "Mew", type: [PokemonTypes.psychic] },
  { name: "Chikorita", type: [PokemonTypes.grass] },
  { name: "Bayleef", type: [PokemonTypes.grass] },
  { name: "Meganium", type: [PokemonTypes.grass] },
  { name: "Cyndaquil", type: [PokemonTypes.fire] },
  { name: "Quilava", type: [PokemonTypes.fire] },
  { name: "Typhlosion", type: [PokemonTypes.fire] },
  { name: "Totodile", type: [PokemonTypes.water] },
  { name: "Croconaw", type: [PokemonTypes.water] },
  { name: "Feraligatr", type: [PokemonTypes.water] },
  { name: "Sentret", type: [PokemonTypes.normal] },
  { name: "Furret", type: [PokemonTypes.normal] },
  { name: "Hoothoot", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Noctowl", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Ledyba", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Ledian", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Spinarak", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Ariados", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Crobat", type: [PokemonTypes.poison, PokemonTypes.flying] },
  { name: "Chinchou", type: [PokemonTypes.water, PokemonTypes.electric] },
  { name: "Lanturn", type: [PokemonTypes.water, PokemonTypes.electric] },
  { name: "Pichu", type: [PokemonTypes.electric] },
  { name: "Cleffa", type: [PokemonTypes.normal] },
  { name: "Igglybuff", type: [PokemonTypes.normal] },
  { name: "Togepi", type: [PokemonTypes.normal] },
  { name: "Togetic", type: [PokemonTypes.flying] },
  { name: "Natu", type: [PokemonTypes.psychic, PokemonTypes.flying] },
  { name: "Xatu", type: [PokemonTypes.psychic, PokemonTypes.flying] },
  { name: "Mareep", type: [PokemonTypes.electric] },
  { name: "Flaaffy", type: [PokemonTypes.electric] },
  { name: "Ampharos", type: [PokemonTypes.electric] },
  { name: "Bellossom", type: [PokemonTypes.grass] },
  { name: "Marill", type: [PokemonTypes.water] },
  { name: "Azumarill", type: [PokemonTypes.water] },
  { name: "Sudowoodo", type: [PokemonTypes.rock] },
  { name: "Politoed", type: [PokemonTypes.water] },
  { name: "Hoppip", type: [PokemonTypes.grass, PokemonTypes.flying] },
  { name: "Skiploom", type: [PokemonTypes.grass, PokemonTypes.flying] },
  { name: "Jumpluff", type: [PokemonTypes.grass, PokemonTypes.flying] },
  { name: "Aipom", type: [PokemonTypes.normal] },
  { name: "Sunkern", type: [PokemonTypes.grass] },
  { name: "Sunflora", type: [PokemonTypes.grass] },
  { name: "Yanma", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Wooper", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Quagsire", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Espeon", type: [PokemonTypes.psychic] },
  { name: "Umbreon", type: [PokemonTypes.dark] },
  { name: "Murkrow", type: [PokemonTypes.dark, PokemonTypes.flying] },
  { name: "Slowking", type: [PokemonTypes.water, PokemonTypes.psychic] },
  { name: "Misdreavus", type: [PokemonTypes.ghost] },
  { name: "Unown", type: [PokemonTypes.psychic] },
  { name: "Wobbuffet", type: [PokemonTypes.psychic] },
  { name: "Girafarig", type: [PokemonTypes.normal, PokemonTypes.psychic] },
  { name: "Pineco", type: [PokemonTypes.bug] },
  { name: "Forretress", type: [PokemonTypes.bug, PokemonTypes.steel] },
  { name: "Dunsparce", type: [PokemonTypes.normal] },
  { name: "Gligar", type: [PokemonTypes.ground, PokemonTypes.flying] },
  { name: "Steelix", type: [PokemonTypes.steel, PokemonTypes.ground] },
  { name: "Snubbull", type: [PokemonTypes.normal] },
  { name: "Granbull", type: [PokemonTypes.normal] },
  { name: "Qwilfish", type: [PokemonTypes.water, PokemonTypes.poison] },
  { name: "Scizor", type: [PokemonTypes.bug, PokemonTypes.steel] },
  { name: "Shuckle", type: [PokemonTypes.bug, PokemonTypes.rock] },
  { name: "Heracross", type: [PokemonTypes.bug, PokemonTypes.fighting] },
  { name: "Sneasel", type: [PokemonTypes.dark, PokemonTypes.ice] },
  { name: "Teddiursa", type: [PokemonTypes.normal] },
  { name: "Ursaring", type: [PokemonTypes.normal] },
  { name: "Slugma", type: [PokemonTypes.fire] },
  { name: "Magcargo", type: [PokemonTypes.fire, PokemonTypes.rock] },
  { name: "Swinub", type: [PokemonTypes.ice, PokemonTypes.ground] },
  { name: "Piloswine", type: [PokemonTypes.ice, PokemonTypes.ground] },
  { name: "Corsola", type: [PokemonTypes.water, PokemonTypes.rock] },
  { name: "Remoraid", type: [PokemonTypes.water] },
  { name: "Octillery", type: [PokemonTypes.water] },
  { name: "Delibird", type: [PokemonTypes.ice, PokemonTypes.flying] },
  { name: "Mantine", type: [PokemonTypes.water, PokemonTypes.flying] },
  { name: "Skarmory", type: [PokemonTypes.steel, PokemonTypes.flying] },
  { name: "Houndour", type: [PokemonTypes.dark, PokemonTypes.fire] },
  { name: "Houndoom", type: [PokemonTypes.dark, PokemonTypes.fire] },
  { name: "Kingdra", type: [PokemonTypes.water, PokemonTypes.dragon] },
  { name: "Phanpy", type: [PokemonTypes.ground] },
  { name: "Donphan", type: [PokemonTypes.ground] },
  { name: "Porygon2", type: [PokemonTypes.normal] },
  { name: "Stantler", type: [PokemonTypes.normal] },
  { name: "Smeargle", type: [PokemonTypes.normal] },
  { name: "Tyrogue", type: [PokemonTypes.fighting] },
  { name: "Hitmontop", type: [PokemonTypes.fighting] },
  { name: "Smoochum", type: [PokemonTypes.ice, PokemonTypes.psychic] },
  { name: "Elekid", type: [PokemonTypes.electric] },
  { name: "Magby", type: [PokemonTypes.fire] },
  { name: "Miltank", type: [PokemonTypes.normal] },
  { name: "Blissey", type: [PokemonTypes.normal] },
  { name: "Raikou", type: [PokemonTypes.electric] },
  { name: "Entei", type: [PokemonTypes.fire] },
  { name: "Suicune", type: [PokemonTypes.water] },
  { name: "Larvitar", type: [PokemonTypes.rock, PokemonTypes.ground] },
  { name: "Pupitar", type: [PokemonTypes.rock, PokemonTypes.ground] },
  { name: "Tyranitar", type: [PokemonTypes.rock, PokemonTypes.dark] },
  { name: "Lugia", type: [PokemonTypes.psychic, PokemonTypes.flying] },
  { name: "Ho-Oh", type: [PokemonTypes.fire, PokemonTypes.flying] },
  { name: "Celebi", type: [PokemonTypes.psychic, PokemonTypes.grass] },
  { name: "Treecko", type: [PokemonTypes.grass] },
  { name: "Grovyle", type: [PokemonTypes.grass] },
  { name: "Sceptile", type: [PokemonTypes.grass] },
  { name: "Torchic", type: [PokemonTypes.fire] },
  { name: "Combusken", type: [PokemonTypes.fire, PokemonTypes.fighting] },
  { name: "Blaziken", type: [PokemonTypes.fire, PokemonTypes.fighting] },
  { name: "Mudkip", type: [PokemonTypes.water] },
  { name: "Marshtomp", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Swampert", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Poochyena", type: [PokemonTypes.dark] },
  { name: "Mightyena", type: [PokemonTypes.dark] },
  { name: "Zigzagoon", type: [PokemonTypes.normal] },
  { name: "Linoone", type: [PokemonTypes.normal] },
  { name: "Wurmple", type: [PokemonTypes.bug] },
  { name: "Silcoon", type: [PokemonTypes.bug] },
  { name: "Beautifly", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Cascoon", type: [PokemonTypes.bug] },
  { name: "Dustox", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Lotad", type: [PokemonTypes.water, PokemonTypes.grass] },
  { name: "Lombre", type: [PokemonTypes.water, PokemonTypes.grass] },
  { name: "Ludicolo", type: [PokemonTypes.water, PokemonTypes.grass] },
  { name: "Seedot", type: [PokemonTypes.grass] },
  { name: "Nuzleaf", type: [PokemonTypes.grass, PokemonTypes.dark] },
  { name: "Shiftry", type: [PokemonTypes.grass, PokemonTypes.dark] },
  { name: "Taillow", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Swellow", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Wingull", type: [PokemonTypes.water, PokemonTypes.flying] },
  { name: "Pelipper", type: [PokemonTypes.water, PokemonTypes.flying] },
  { name: "Ralts", type: [PokemonTypes.psychic] },
  { name: "Kirlia", type: [PokemonTypes.psychic] },
  { name: "Gardevoir", type: [PokemonTypes.psychic] },
  { name: "Surskit", type: [PokemonTypes.bug, PokemonTypes.water] },
  { name: "Masquerain", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Shroomish", type: [PokemonTypes.grass] },
  { name: "Breloom", type: [PokemonTypes.grass, PokemonTypes.fighting] },
  { name: "Slakoth", type: [PokemonTypes.normal] },
  { name: "Vigoroth", type: [PokemonTypes.normal] },
  { name: "Slaking", type: [PokemonTypes.normal] },
  { name: "Nincada", type: [PokemonTypes.bug, PokemonTypes.ground] },
  { name: "Ninjask", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Shedinja", type: [PokemonTypes.bug, PokemonTypes.ghost] },
  { name: "Whismur", type: [PokemonTypes.normal] },
  { name: "Loudred", type: [PokemonTypes.normal] },
  { name: "Exploud", type: [PokemonTypes.normal] },
  { name: "Makuhita", type: [PokemonTypes.fighting] },
  { name: "Hariyama", type: [PokemonTypes.fighting] },
  { name: "Azurill", type: [PokemonTypes.normal] },
  { name: "Nosepass", type: [PokemonTypes.rock] },
  { name: "Skitty", type: [PokemonTypes.normal] },
  { name: "Delcatty", type: [PokemonTypes.normal] },
  { name: "Sableye", type: [PokemonTypes.dark, PokemonTypes.ghost] },
  { name: "Mawile", type: [PokemonTypes.steel] },
  { name: "Aron", type: [PokemonTypes.steel, PokemonTypes.rock] },
  { name: "Lairon", type: [PokemonTypes.steel, PokemonTypes.rock] },
  { name: "Aggron", type: [PokemonTypes.steel, PokemonTypes.rock] },
  { name: "Meditite", type: [PokemonTypes.fighting, PokemonTypes.psychic] },
  { name: "Medicham", type: [PokemonTypes.fighting, PokemonTypes.psychic] },
  { name: "Electrike", type: [PokemonTypes.electric] },
  { name: "Manectric", type: [PokemonTypes.electric] },
  { name: "Plusle", type: [PokemonTypes.electric] },
  { name: "Minun", type: [PokemonTypes.electric] },
  { name: "Volbeat", type: [PokemonTypes.bug] },
  { name: "Illumise", type: [PokemonTypes.bug] },
  { name: "Roselia", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Gulpin", type: [PokemonTypes.poison] },
  { name: "Swalot", type: [PokemonTypes.poison] },
  { name: "Carvanha", type: [PokemonTypes.water, PokemonTypes.dark] },
  { name: "Sharpedo", type: [PokemonTypes.water, PokemonTypes.dark] },
  { name: "Wailmer", type: [PokemonTypes.water] },
  { name: "Wailord", type: [PokemonTypes.water] },
  { name: "Numel", type: [PokemonTypes.fire, PokemonTypes.ground] },
  { name: "Camerupt", type: [PokemonTypes.fire, PokemonTypes.ground] },
  { name: "Torkoal", type: [PokemonTypes.fire] },
  { name: "Spoink", type: [PokemonTypes.psychic] },
  { name: "Grumpig", type: [PokemonTypes.psychic] },
  { name: "Spinda", type: [PokemonTypes.normal] },
  { name: "Trapinch", type: [PokemonTypes.ground] },
  { name: "Vibrava", type: [PokemonTypes.ground, PokemonTypes.dragon] },
  { name: "Flygon", type: [PokemonTypes.ground, PokemonTypes.dragon] },
  { name: "Cacnea", type: [PokemonTypes.grass] },
  { name: "Cacturne", type: [PokemonTypes.grass, PokemonTypes.dark] },
  { name: "Swablu", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Altaria", type: [PokemonTypes.dragon, PokemonTypes.flying] },
  { name: "Zangoose", type: [PokemonTypes.normal] },
  { name: "Seviper", type: [PokemonTypes.poison] },
  { name: "Lunatone", type: [PokemonTypes.rock, PokemonTypes.psychic] },
  { name: "Solrock", type: [PokemonTypes.rock, PokemonTypes.psychic] },
  { name: "Barboach", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Whiscash", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Corphish", type: [PokemonTypes.water] },
  { name: "Crawdaunt", type: [PokemonTypes.water, PokemonTypes.dark] },
  { name: "Baltoy", type: [PokemonTypes.ground, PokemonTypes.psychic] },
  { name: "Claydol", type: [PokemonTypes.ground, PokemonTypes.psychic] },
  { name: "Lileep", type: [PokemonTypes.rock, PokemonTypes.grass] },
  { name: "Cradily", type: [PokemonTypes.rock, PokemonTypes.grass] },
  { name: "Anorith", type: [PokemonTypes.rock, PokemonTypes.bug] },
  { name: "Armaldo", type: [PokemonTypes.rock, PokemonTypes.bug] },
  { name: "Feebas", type: [PokemonTypes.water] },
  { name: "Milotic", type: [PokemonTypes.water] },
  { name: "Castform", type: [PokemonTypes.normal] },
  { name: "Kecleon", type: [PokemonTypes.normal] },
  { name: "Shuppet", type: [PokemonTypes.ghost] },
  { name: "Banette", type: [PokemonTypes.ghost] },
  { name: "Duskull", type: [PokemonTypes.ghost] },
  { name: "Dusclops", type: [PokemonTypes.ghost] },
  { name: "Tropius", type: [PokemonTypes.grass, PokemonTypes.flying] },
  { name: "Chimecho", type: [PokemonTypes.psychic] },
  { name: "Absol", type: [PokemonTypes.dark] },
  { name: "Wynaut", type: [PokemonTypes.psychic] },
  { name: "Snorunt", type: [PokemonTypes.ice] },
  { name: "Glalie", type: [PokemonTypes.ice] },
  { name: "Spheal", type: [PokemonTypes.ice, PokemonTypes.water] },
  { name: "Sealeo", type: [PokemonTypes.ice, PokemonTypes.water] },
  { name: "Walrein", type: [PokemonTypes.ice, PokemonTypes.water] },
  { name: "Clamperl", type: [PokemonTypes.water] },
  { name: "Huntail", type: [PokemonTypes.water] },
  { name: "Gorebyss", type: [PokemonTypes.water] },
  { name: "Relicanth", type: [PokemonTypes.water, PokemonTypes.rock] },
  { name: "Luvdisc", type: [PokemonTypes.water] },
  { name: "Bagon", type: [PokemonTypes.dragon] },
  { name: "Shelgon", type: [PokemonTypes.dragon] },
  { name: "Salamence", type: [PokemonTypes.dragon, PokemonTypes.flying] },
  { name: "Beldum", type: [PokemonTypes.steel, PokemonTypes.psychic] },
  { name: "Metang", type: [PokemonTypes.steel, PokemonTypes.psychic] },
  { name: "Metagross", type: [PokemonTypes.steel, PokemonTypes.psychic] },
  { name: "Regirock", type: [PokemonTypes.rock] },
  { name: "Regice", type: [PokemonTypes.ice] },
  { name: "Registeel", type: [PokemonTypes.steel] },
  { name: "Latias", type: [PokemonTypes.dragon, PokemonTypes.psychic] },
  { name: "Latios", type: [PokemonTypes.dragon, PokemonTypes.psychic] },
  { name: "Kyogre", type: [PokemonTypes.water] },
  { name: "Groudon", type: [PokemonTypes.ground] },
  { name: "Rayquaza", type: [PokemonTypes.dragon, PokemonTypes.flying] },
  { name: "Jirachi", type: [PokemonTypes.steel, PokemonTypes.psychic] },
  { name: "Deoxys", type: [PokemonTypes.psychic] },
  { name: "Turtwig", type: [PokemonTypes.grass] },
  { name: "Grotle", type: [PokemonTypes.grass] },
  { name: "Torterra", type: [PokemonTypes.grass, PokemonTypes.ground] },
  { name: "Chimchar", type: [PokemonTypes.fire] },
  { name: "Monferno", type: [PokemonTypes.fire, PokemonTypes.fighting] },
  { name: "Infernape", type: [PokemonTypes.fire, PokemonTypes.fighting] },
  { name: "Piplup", type: [PokemonTypes.water] },
  { name: "Prinplup", type: [PokemonTypes.water] },
  { name: "Empoleon", type: [PokemonTypes.water, PokemonTypes.steel] },
  { name: "Starly", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Staravia", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Staraptor", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Bidoof", type: [PokemonTypes.normal] },
  { name: "Bibarel", type: [PokemonTypes.normal, PokemonTypes.water] },
  { name: "Kricketot", type: [PokemonTypes.bug] },
  { name: "Kricketune", type: [PokemonTypes.bug] },
  { name: "Shinx", type: [PokemonTypes.electric] },
  { name: "Luxio", type: [PokemonTypes.electric] },
  { name: "Luxray", type: [PokemonTypes.electric] },
  { name: "Budew", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Roserade", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Cranidos", type: [PokemonTypes.rock] },
  { name: "Rampardos", type: [PokemonTypes.rock] },
  { name: "Shieldon", type: [PokemonTypes.rock, PokemonTypes.steel] },
  { name: "Bastiodon", type: [PokemonTypes.rock, PokemonTypes.steel] },
  { name: "Burmy", type: [PokemonTypes.bug] },
  { name: "Wormadam", type: [PokemonTypes.bug, PokemonTypes.grass] },
  { name: "Mothim", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Combee", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Vespiquen", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Pachirisu", type: [PokemonTypes.electric] },
  { name: "Buizel", type: [PokemonTypes.water] },
  { name: "Floatzel", type: [PokemonTypes.water] },
  { name: "Cherubi", type: [PokemonTypes.grass] },
  { name: "Cherrim", type: [PokemonTypes.grass] },
  { name: "Shellos", type: [PokemonTypes.water] },
  { name: "Gastrodon", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Ambipom", type: [PokemonTypes.normal] },
  { name: "Drifloon", type: [PokemonTypes.ghost, PokemonTypes.flying] },
  { name: "Drifblim", type: [PokemonTypes.ghost, PokemonTypes.flying] },
  { name: "Buneary", type: [PokemonTypes.normal] },
  { name: "Lopunny", type: [PokemonTypes.normal] },
  { name: "Mismagius", type: [PokemonTypes.ghost] },
  { name: "Honchkrow", type: [PokemonTypes.dark, PokemonTypes.flying] },
  { name: "Glameow", type: [PokemonTypes.normal] },
  { name: "Purugly", type: [PokemonTypes.normal] },
  { name: "Chingling", type: [PokemonTypes.psychic] },
  { name: "Stunky", type: [PokemonTypes.poison, PokemonTypes.dark] },
  { name: "Skuntank", type: [PokemonTypes.poison, PokemonTypes.dark] },
  { name: "Bronzor", type: [PokemonTypes.steel, PokemonTypes.psychic] },
  { name: "Bronzong", type: [PokemonTypes.steel, PokemonTypes.psychic] },
  { name: "Bonsly", type: [PokemonTypes.rock] },
  { name: "Mime Jr.", type: [PokemonTypes.psychic] },
  { name: "Happiny", type: [PokemonTypes.normal] },
  { name: "Chatot", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Spiritomb", type: [PokemonTypes.ghost, PokemonTypes.dark] },
  { name: "Gible", type: [PokemonTypes.dragon, PokemonTypes.ground] },
  { name: "Gabite", type: [PokemonTypes.dragon, PokemonTypes.ground] },
  { name: "Garchomp", type: [PokemonTypes.dragon, PokemonTypes.ground] },
  { name: "Munchlax", type: [PokemonTypes.normal] },
  { name: "Riolu", type: [PokemonTypes.fighting] },
  { name: "Lucario", type: [PokemonTypes.fighting, PokemonTypes.steel] },
  { name: "Hippopotas", type: [PokemonTypes.ground] },
  { name: "Hippowdon", type: [PokemonTypes.ground] },
  { name: "Skorupi", type: [PokemonTypes.poison, PokemonTypes.bug] },
  { name: "Drapion", type: [PokemonTypes.poison, PokemonTypes.dark] },
  { name: "Croagunk", type: [PokemonTypes.poison, PokemonTypes.fighting] },
  { name: "Toxicroak", type: [PokemonTypes.poison, PokemonTypes.fighting] },
  { name: "Carnivine", type: [PokemonTypes.grass] },
  { name: "Finneon", type: [PokemonTypes.water] },
  { name: "Lumineon", type: [PokemonTypes.water] },
  { name: "Mantyke", type: [PokemonTypes.water, PokemonTypes.flying] },
  { name: "Snover", type: [PokemonTypes.grass, PokemonTypes.ice] },
  { name: "Abomasnow", type: [PokemonTypes.grass, PokemonTypes.ice] },
  { name: "Weavile", type: [PokemonTypes.dark, PokemonTypes.ice] },
  { name: "Magnezone", type: [PokemonTypes.electric, PokemonTypes.steel] },
  { name: "Lickilicky", type: [PokemonTypes.normal] },
  { name: "Rhyperior", type: [PokemonTypes.ground, PokemonTypes.rock] },
  { name: "Tangrowth", type: [PokemonTypes.grass] },
  { name: "Electivire", type: [PokemonTypes.electric] },
  { name: "Magmortar", type: [PokemonTypes.fire] },
  { name: "Togekiss", type: [PokemonTypes.flying] },
  { name: "Yanmega", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Leafeon", type: [PokemonTypes.grass] },
  { name: "Glaceon", type: [PokemonTypes.ice] },
  { name: "Gliscor", type: [PokemonTypes.ground, PokemonTypes.flying] },
  { name: "Mamoswine", type: [PokemonTypes.ice, PokemonTypes.ground] },
  { name: "Porygon-Z", type: [PokemonTypes.normal] },
  { name: "Gallade", type: [PokemonTypes.psychic, PokemonTypes.fighting] },
  { name: "Probopass", type: [PokemonTypes.rock, PokemonTypes.steel] },
  { name: "Dusknoir", type: [PokemonTypes.ghost] },
  { name: "Froslass", type: [PokemonTypes.ice, PokemonTypes.ghost] },
  { name: "Rotom", type: [PokemonTypes.electric, PokemonTypes.ghost] },
  { name: "Uxie", type: [PokemonTypes.psychic] },
  { name: "Mesprit", type: [PokemonTypes.psychic] },
  { name: "Azelf", type: [PokemonTypes.psychic] },
  { name: "Dialga", type: [PokemonTypes.steel, PokemonTypes.dragon] },
  { name: "Palkia", type: [PokemonTypes.water, PokemonTypes.dragon] },
  { name: "Heatran", type: [PokemonTypes.fire, PokemonTypes.steel] },
  { name: "Regigigas", type: [PokemonTypes.normal] },
  { name: "Giratina", type: [PokemonTypes.ghost, PokemonTypes.dragon] },
  { name: "Cresselia", type: [PokemonTypes.psychic] },
  { name: "Phione", type: [PokemonTypes.water] },
  { name: "Manaphy", type: [PokemonTypes.water] },
  { name: "Darkrai", type: [PokemonTypes.dark] },
  { name: "Shaymin", type: [PokemonTypes.grass] },
  { name: "Arceus", type: [PokemonTypes.normal] },
  { name: "Victini", type: [PokemonTypes.psychic, PokemonTypes.fire] },
  { name: "Snivy", type: [PokemonTypes.grass] },
  { name: "Servine", type: [PokemonTypes.grass] },
  { name: "Serperior", type: [PokemonTypes.grass] },
  { name: "Tepig", type: [PokemonTypes.fire] },
  { name: "Pignite", type: [PokemonTypes.fire, PokemonTypes.fighting] },
  { name: "Emboar", type: [PokemonTypes.fire, PokemonTypes.fighting] },
  { name: "Oshawott", type: [PokemonTypes.water] },
  { name: "Dewott", type: [PokemonTypes.water] },
  { name: "Samurott", type: [PokemonTypes.water] },
  { name: "Patrat", type: [PokemonTypes.normal] },
  { name: "Watchog", type: [PokemonTypes.normal] },
  { name: "Lillipup", type: [PokemonTypes.normal] },
  { name: "Herdier", type: [PokemonTypes.normal] },
  { name: "Stoutland", type: [PokemonTypes.normal] },
  { name: "Purrloin", type: [PokemonTypes.dark] },
  { name: "Liepard", type: [PokemonTypes.dark] },
  { name: "Pansage", type: [PokemonTypes.grass] },
  { name: "Simisage", type: [PokemonTypes.grass] },
  { name: "Pansear", type: [PokemonTypes.fire] },
  { name: "Simisear", type: [PokemonTypes.fire] },
  { name: "Panpour", type: [PokemonTypes.water] },
  { name: "Simipour", type: [PokemonTypes.water] },
  { name: "Munna", type: [PokemonTypes.psychic] },
  { name: "Musharna", type: [PokemonTypes.psychic] },
  { name: "Pidove", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Tranquill", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Unfezant", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Blitzle", type: [PokemonTypes.electric] },
  { name: "Zebstrika", type: [PokemonTypes.electric] },
  { name: "Roggenrola", type: [PokemonTypes.rock] },
  { name: "Boldore", type: [PokemonTypes.rock] },
  { name: "Gigalith", type: [PokemonTypes.rock] },
  { name: "Woobat", type: [PokemonTypes.psychic, PokemonTypes.flying] },
  { name: "Swoobat", type: [PokemonTypes.psychic, PokemonTypes.flying] },
  { name: "Drilbur", type: [PokemonTypes.ground] },
  { name: "Excadrill", type: [PokemonTypes.ground, PokemonTypes.steel] },
  { name: "Audino", type: [PokemonTypes.normal] },
  { name: "Timburr", type: [PokemonTypes.fighting] },
  { name: "Gurdurr", type: [PokemonTypes.fighting] },
  { name: "Conkeldurr", type: [PokemonTypes.fighting] },
  { name: "Tympole", type: [PokemonTypes.water] },
  { name: "Palpitoad", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Seismitoad", type: [PokemonTypes.water, PokemonTypes.ground] },
  { name: "Throh", type: [PokemonTypes.fighting] },
  { name: "Sawk", type: [PokemonTypes.fighting] },
  { name: "Sewaddle", type: [PokemonTypes.bug, PokemonTypes.grass] },
  { name: "Swadloon", type: [PokemonTypes.bug, PokemonTypes.grass] },
  { name: "Leavanny", type: [PokemonTypes.bug, PokemonTypes.grass] },
  { name: "Venipede", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Whirlipede", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Scolipede", type: [PokemonTypes.bug, PokemonTypes.poison] },
  { name: "Cottonee", type: [PokemonTypes.grass] },
  { name: "Whimsicott", type: [PokemonTypes.grass] },
  { name: "Petilil", type: [PokemonTypes.grass] },
  { name: "Lilligant", type: [PokemonTypes.grass] },
  { name: "Basculin", type: [PokemonTypes.water] },
  { name: "Sandile", type: [PokemonTypes.ground, PokemonTypes.dark] },
  { name: "Krokorok", type: [PokemonTypes.ground, PokemonTypes.dark] },
  { name: "Krookodile", type: [PokemonTypes.ground, PokemonTypes.dark] },
  { name: "Darumaka", type: [PokemonTypes.fire] },
  { name: "Darmanitan", type: [PokemonTypes.fire] },
  { name: "Maractus", type: [PokemonTypes.grass] },
  { name: "Dwebble", type: [PokemonTypes.bug, PokemonTypes.rock] },
  { name: "Crustle", type: [PokemonTypes.bug, PokemonTypes.rock] },
  { name: "Scraggy", type: [PokemonTypes.dark, PokemonTypes.fighting] },
  { name: "Scrafty", type: [PokemonTypes.dark, PokemonTypes.fighting] },
  { name: "Sigilyph", type: [PokemonTypes.psychic, PokemonTypes.flying] },
  { name: "Yamask", type: [PokemonTypes.ghost] },
  { name: "Cofagrigus", type: [PokemonTypes.ghost] },
  { name: "Tirtouga", type: [PokemonTypes.water, PokemonTypes.rock] },
  { name: "Carracosta", type: [PokemonTypes.water, PokemonTypes.rock] },
  { name: "Archen", type: [PokemonTypes.rock, PokemonTypes.flying] },
  { name: "Archeops", type: [PokemonTypes.rock, PokemonTypes.flying] },
  { name: "Trubbish", type: [PokemonTypes.poison] },
  { name: "Garbodor", type: [PokemonTypes.poison] },
  { name: "Zorua", type: [PokemonTypes.dark] },
  { name: "Zoroark", type: [PokemonTypes.dark] },
  { name: "Minccino", type: [PokemonTypes.normal] },
  { name: "Cinccino", type: [PokemonTypes.normal] },
  { name: "Gothita", type: [PokemonTypes.psychic] },
  { name: "Gothorita", type: [PokemonTypes.psychic] },
  { name: "Gothitelle", type: [PokemonTypes.psychic] },
  { name: "Solosis", type: [PokemonTypes.psychic] },
  { name: "Duosion", type: [PokemonTypes.psychic] },
  { name: "Reuniclus", type: [PokemonTypes.psychic] },
  { name: "Ducklett", type: [PokemonTypes.water, PokemonTypes.flying] },
  { name: "Swanna", type: [PokemonTypes.water, PokemonTypes.flying] },
  { name: "Vanillite", type: [PokemonTypes.ice] },
  { name: "Vanillish", type: [PokemonTypes.ice] },
  { name: "Vanilluxe", type: [PokemonTypes.ice] },
  { name: "Deerling", type: [PokemonTypes.normal, PokemonTypes.grass] },
  { name: "Sawsbuck", type: [PokemonTypes.normal, PokemonTypes.grass] },
  { name: "Emolga", type: [PokemonTypes.electric, PokemonTypes.flying] },
  { name: "Karrablast", type: [PokemonTypes.bug] },
  { name: "Escavalier", type: [PokemonTypes.bug, PokemonTypes.steel] },
  { name: "Foongus", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Amoonguss", type: [PokemonTypes.grass, PokemonTypes.poison] },
  { name: "Frillish", type: [PokemonTypes.water, PokemonTypes.ghost] },
  { name: "Jellicent", type: [PokemonTypes.water, PokemonTypes.ghost] },
  { name: "Alomomola", type: [PokemonTypes.water] },
  { name: "Joltik", type: [PokemonTypes.bug, PokemonTypes.electric] },
  { name: "Galvantula", type: [PokemonTypes.bug, PokemonTypes.electric] },
  { name: "Ferroseed", type: [PokemonTypes.grass, PokemonTypes.steel] },
  { name: "Ferrothorn", type: [PokemonTypes.grass, PokemonTypes.steel] },
  { name: "Klink", type: [PokemonTypes.steel] },
  { name: "Klang", type: [PokemonTypes.steel] },
  { name: "Klinklang", type: [PokemonTypes.steel] },
  { name: "Tynamo", type: [PokemonTypes.electric] },
  { name: "Eelektrik", type: [PokemonTypes.electric] },
  { name: "Eelektross", type: [PokemonTypes.electric] },
  { name: "Elgyem", type: [PokemonTypes.psychic] },
  { name: "Beheeyem", type: [PokemonTypes.psychic] },
  { name: "Litwick", type: [PokemonTypes.ghost, PokemonTypes.fire] },
  { name: "Lampent", type: [PokemonTypes.ghost, PokemonTypes.fire] },
  { name: "Chandelure", type: [PokemonTypes.ghost, PokemonTypes.fire] },
  { name: "Axew", type: [PokemonTypes.dragon] },
  { name: "Fraxure", type: [PokemonTypes.dragon] },
  { name: "Haxorus", type: [PokemonTypes.dragon] },
  { name: "Cubchoo", type: [PokemonTypes.ice] },
  { name: "Beartic", type: [PokemonTypes.ice] },
  { name: "Cryogonal", type: [PokemonTypes.ice] },
  { name: "Shelmet", type: [PokemonTypes.bug] },
  { name: "Accelgor", type: [PokemonTypes.bug] },
  { name: "Stunfisk", type: [PokemonTypes.ground, PokemonTypes.electric] },
  { name: "Mienfoo", type: [PokemonTypes.fighting] },
  { name: "Mienshao", type: [PokemonTypes.fighting] },
  { name: "Druddigon", type: [PokemonTypes.dragon] },
  { name: "Golett", type: [PokemonTypes.ground, PokemonTypes.ghost] },
  { name: "Golurk", type: [PokemonTypes.ground, PokemonTypes.ghost] },
  { name: "Pawniard", type: [PokemonTypes.dark, PokemonTypes.steel] },
  { name: "Bisharp", type: [PokemonTypes.dark, PokemonTypes.steel] },
  { name: "Bouffalant", type: [PokemonTypes.normal] },
  { name: "Rufflet", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Braviary", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Vullaby", type: [PokemonTypes.dark, PokemonTypes.flying] },
  { name: "Mandibuzz", type: [PokemonTypes.dark, PokemonTypes.flying] },
  { name: "Heatmor", type: [PokemonTypes.fire] },
  { name: "Durant", type: [PokemonTypes.bug, PokemonTypes.steel] },
  { name: "Deino", type: [PokemonTypes.dark, PokemonTypes.dragon] },
  { name: "Zweilous", type: [PokemonTypes.dark, PokemonTypes.dragon] },
  { name: "Hydreigon", type: [PokemonTypes.dark, PokemonTypes.dragon] },
  { name: "Larvesta", type: [PokemonTypes.bug, PokemonTypes.fire] },
  { name: "Volcarona", type: [PokemonTypes.bug, PokemonTypes.fire] },
  { name: "Cobalion", type: [PokemonTypes.steel, PokemonTypes.fighting] },
  { name: "Terrakion", type: [PokemonTypes.rock, PokemonTypes.fighting] },
  { name: "Virizion", type: [PokemonTypes.grass, PokemonTypes.fighting] },
  { name: "Tornadus", type: [PokemonTypes.flying] },
  { name: "Thundurus", type: [PokemonTypes.electric, PokemonTypes.flying] },
  { name: "Reshiram", type: [PokemonTypes.dragon, PokemonTypes.fire] },
  { name: "Zekrom", type: [PokemonTypes.dragon, PokemonTypes.electric] },
  { name: "Landorus", type: [PokemonTypes.ground, PokemonTypes.flying] },
  { name: "Kyurem", type: [PokemonTypes.dragon, PokemonTypes.ice] },
  { name: "Keldeo", type: [PokemonTypes.water, PokemonTypes.fighting] },
  { name: "Meloetta", type: [PokemonTypes.normal, PokemonTypes.psychic] },
  { name: "Genesect", type: [PokemonTypes.bug, PokemonTypes.steel] },
  { name: "Chespin", type: [PokemonTypes.grass] },
  { name: "Quilladin", type: [PokemonTypes.grass] },
  { name: "Chesnaught", type: [PokemonTypes.grass, PokemonTypes.fighting] },
  { name: "Fennekin", type: [PokemonTypes.fire] },
  { name: "Braixen", type: [PokemonTypes.fire] },
  { name: "Delphox", type: [PokemonTypes.fire, PokemonTypes.psychic] },
  { name: "Froakie", type: [PokemonTypes.water] },
  { name: "Frogadier", type: [PokemonTypes.water] },
  { name: "Greninja", type: [PokemonTypes.water, PokemonTypes.dark] },
  { name: "Bunnelby", type: [PokemonTypes.normal] },
  { name: "Diggersby", type: [PokemonTypes.normal, PokemonTypes.ground] },
  { name: "Fletchling", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Fletchinder", type: [PokemonTypes.fire, PokemonTypes.flying] },
  { name: "Talonflame", type: [PokemonTypes.fire, PokemonTypes.flying] },
  { name: "Scatterbug", type: [PokemonTypes.bug] },
  { name: "Spewpa", type: [PokemonTypes.bug] },
  { name: "Vivillon", type: [PokemonTypes.bug, PokemonTypes.flying] },
  { name: "Litleo", type: [PokemonTypes.fire, PokemonTypes.normal] },
  { name: "Pyroar", type: [PokemonTypes.fire, PokemonTypes.normal] },
  { name: "Flabébé", type: [PokemonTypes.normal] },
  { name: "Floette", type: [PokemonTypes.normal] },
  { name: "Florges", type: [PokemonTypes.normal] },
  { name: "Skiddo", type: [PokemonTypes.grass] },
  { name: "Gogoat", type: [PokemonTypes.grass] },
  { name: "Pancham", type: [PokemonTypes.fighting] },
  { name: "Pangoro", type: [PokemonTypes.fighting, PokemonTypes.dark] },
  { name: "Furfrou", type: [PokemonTypes.normal] },
  { name: "Espurr", type: [PokemonTypes.psychic] },
  { name: "Meowstic", type: [PokemonTypes.psychic] },
  { name: "Honedge", type: [PokemonTypes.steel, PokemonTypes.ghost] },
  { name: "Doublade", type: [PokemonTypes.steel, PokemonTypes.ghost] },
  { name: "Aegislash", type: [PokemonTypes.steel, PokemonTypes.ghost] },
  { name: "Spritzee", type: [PokemonTypes.normal] },
  { name: "Aromatisse", type: [PokemonTypes.normal] },
  { name: "Swirlix", type: [PokemonTypes.normal] },
  { name: "Slurpuff", type: [PokemonTypes.normal] },
  { name: "Inkay", type: [PokemonTypes.dark, PokemonTypes.psychic] },
  { name: "Malamar", type: [PokemonTypes.dark, PokemonTypes.psychic] },
  { name: "Binacle", type: [PokemonTypes.rock, PokemonTypes.water] },
  { name: "Barbaracle", type: [PokemonTypes.rock, PokemonTypes.water] },
  { name: "Skrelp", type: [PokemonTypes.poison, PokemonTypes.water] },
  { name: "Dragalge", type: [PokemonTypes.poison, PokemonTypes.dragon] },
  { name: "Clauncher", type: [PokemonTypes.water] },
  { name: "Clawitzer", type: [PokemonTypes.water] },
  { name: "Helioptile", type: [PokemonTypes.electric, PokemonTypes.normal] },
  { name: "Heliolisk", type: [PokemonTypes.electric, PokemonTypes.normal] },
  { name: "Tyrunt", type: [PokemonTypes.rock, PokemonTypes.dragon] },
  { name: "Tyrantrum", type: [PokemonTypes.rock, PokemonTypes.dragon] },
  { name: "Amaura", type: [PokemonTypes.rock, PokemonTypes.ice] },
  { name: "Aurorus", type: [PokemonTypes.rock, PokemonTypes.ice] },
  { name: "Sylveon", type: [PokemonTypes.normal] },
  { name: "Hawlucha", type: [PokemonTypes.fighting, PokemonTypes.flying] },
  { name: "Dedenne", type: [PokemonTypes.electric] },
  { name: "Carbink", type: [PokemonTypes.rock] },
  { name: "Goomy", type: [PokemonTypes.dragon] },
  { name: "Sliggoo", type: [PokemonTypes.dragon] },
  { name: "Goodra", type: [PokemonTypes.dragon] },
  { name: "Klefki", type: [PokemonTypes.steel] },
  { name: "Phantump", type: [PokemonTypes.ghost, PokemonTypes.grass] },
  { name: "Trevenant", type: [PokemonTypes.ghost, PokemonTypes.grass] },
  { name: "Pumpkaboo", type: [PokemonTypes.ghost, PokemonTypes.grass] },
  { name: "Gourgeist", type: [PokemonTypes.ghost, PokemonTypes.grass] },
  { name: "Bergmite", type: [PokemonTypes.ice] },
  { name: "Avalugg", type: [PokemonTypes.ice] },
  { name: "Noibat", type: [PokemonTypes.flying, PokemonTypes.dragon] },
  { name: "Noivern", type: [PokemonTypes.flying, PokemonTypes.dragon] },
  { name: "Xerneas", type: [PokemonTypes.normal] },
  { name: "Yveltal", type: [PokemonTypes.dark, PokemonTypes.flying] },
  { name: "Zygarde", type: [PokemonTypes.dragon, PokemonTypes.ground] },
  { name: "Diancie", type: [PokemonTypes.rock] },
  { name: "Hoopa", type: [PokemonTypes.psychic, PokemonTypes.ghost] },
  { name: "Volcanion", type: [PokemonTypes.fire, PokemonTypes.water] },
  { name: "Rowlet", type: [PokemonTypes.grass, PokemonTypes.flying] },
  { name: "Dartrix", type: [PokemonTypes.grass, PokemonTypes.flying] },
  { name: "Decidueye", type: [PokemonTypes.grass, PokemonTypes.ghost] },
  { name: "Litten", type: [PokemonTypes.fire] },
  { name: "Torracat", type: [PokemonTypes.fire] },
  { name: "Incineroar", type: [PokemonTypes.fire, PokemonTypes.dark] },
  { name: "Popplio", type: [PokemonTypes.water] },
  { name: "Brionne", type: [PokemonTypes.water] },
  { name: "Primarina", type: [PokemonTypes.water] },
  { name: "Pikipek", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Trumbeak", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Toucannon", type: [PokemonTypes.normal, PokemonTypes.flying] },
  { name: "Yungoos", type: [PokemonTypes.normal] },
  { name: "Gumshoos", type: [PokemonTypes.normal] },
  { name: "Grubbin", type: [PokemonTypes.bug] },
  { name: "Charjabug", type: [PokemonTypes.bug, PokemonTypes.electric] },
  { name: "Vikavolt", type: [PokemonTypes.bug, PokemonTypes.electric] },
  { name: "Crabrawler", type: [PokemonTypes.fighting] },
  { name: "Crabominable", type: [PokemonTypes.fighting, PokemonTypes.ice] },
  { name: "Oricorio", type: [PokemonTypes.fire, PokemonTypes.flying] },
  { name: "Cutiefly", type: [PokemonTypes.bug] },
  { name: "Ribombee", type: [PokemonTypes.bug] },
  { name: "rockruff", type: [PokemonTypes.rock] },
  { name: "Lycanroc", type: [PokemonTypes.rock] },
  { name: "Wishiwashi", type: [PokemonTypes.water] },
  { name: "Mareanie", type: [PokemonTypes.poison, PokemonTypes.water] },
  { name: "Toxapex", type: [PokemonTypes.poison, PokemonTypes.water] },
  { name: "Mudbray", type: [PokemonTypes.ground] },
  { name: "Mudsdale", type: [PokemonTypes.ground] },
  { name: "Dewpider", type: [PokemonTypes.water, PokemonTypes.bug] },
  { name: "Araquanid", type: [PokemonTypes.water, PokemonTypes.bug] },
  { name: "Fomantis", type: [PokemonTypes.grass] },
  { name: "Lurantis", type: [PokemonTypes.grass] },
  { name: "Morelull", type: [PokemonTypes.grass] },
  { name: "Shiinotic", type: [PokemonTypes.grass] },
  { name: "Salandit", type: [PokemonTypes.poison, PokemonTypes.fire] },
  { name: "Salazzle", type: [PokemonTypes.poison, PokemonTypes.fire] },
  { name: "Stufful", type: [PokemonTypes.normal, PokemonTypes.fighting] },
  { name: "Bewear", type: [PokemonTypes.normal, PokemonTypes.fighting] },
  { name: "Bounsweet", type: [PokemonTypes.grass] },
  { name: "Steenee", type: [PokemonTypes.grass] },
  { name: "Tsareena", type: [PokemonTypes.grass] },
  { name: "Comfey", type: [PokemonTypes.normal] },
  { name: "Oranguru", type: [PokemonTypes.normal, PokemonTypes.psychic] },
  { name: "Passimian", type: [PokemonTypes.fighting] },
  { name: "Wimpod", type: [PokemonTypes.bug, PokemonTypes.water] },
  { name: "Golisopod", type: [PokemonTypes.bug, PokemonTypes.water] },
  { name: "Sandygast", type: [PokemonTypes.ghost, PokemonTypes.ground] },
  { name: "Palossand", type: [PokemonTypes.ghost, PokemonTypes.ground] },
  { name: "Pyukumuku", type: [PokemonTypes.water] },
  { name: "Type: Null", type: [PokemonTypes.normal] },
  { name: "Silvally", type: [PokemonTypes.normal] },
  { name: "Minior", type: [PokemonTypes.rock, PokemonTypes.flying] },
  { name: "Komala", type: [PokemonTypes.normal] },
  { name: "Turtonator", type: [PokemonTypes.fire, PokemonTypes.dragon] },
  { name: "Togedemaru", type: [PokemonTypes.electric, PokemonTypes.steel] },
  { name: "Mimikyu", type: [PokemonTypes.ghost] },
  { name: "Bruxish", type: [PokemonTypes.water, PokemonTypes.psychic] },
  { name: "Drampa", type: [PokemonTypes.normal, PokemonTypes.dragon] },
  { name: "Dhelmise", type: [PokemonTypes.ghost, PokemonTypes.grass] },
  { name: "Jangmo-o", type: [PokemonTypes.dragon] },
  { name: "Hakamo-o", type: [PokemonTypes.dragon, PokemonTypes.fighting] },
  { name: "Kommo-o", type: [PokemonTypes.dragon, PokemonTypes.fighting] },
  { name: "Tapu Koko", type: [PokemonTypes.electric] },
  { name: "Tapu Lele", type: [PokemonTypes.psychic] },
  { name: "Tapu Bulu", type: [PokemonTypes.grass] },
  { name: "Tapu Fini", type: [PokemonTypes.water] },
  { name: "Cosmog", type: [PokemonTypes.psychic] },
  { name: "Cosmoem", type: [PokemonTypes.psychic] },
  { name: "Solgaleo", type: [PokemonTypes.psychic, PokemonTypes.steel] },
  { name: "Lunala", type: [PokemonTypes.psychic, PokemonTypes.ghost] },
  { name: "Nihilego", type: [PokemonTypes.rock, PokemonTypes.poison] },
  { name: "Buzzwole", type: [PokemonTypes.bug, PokemonTypes.fighting] },
  { name: "Pheromosa", type: [PokemonTypes.bug, PokemonTypes.fighting] },
  { name: "Xurkitree", type: [PokemonTypes.electric] },
  { name: "Celesteela", type: [PokemonTypes.steel, PokemonTypes.flying] },
  { name: "Kartana", type: [PokemonTypes.grass, PokemonTypes.steel] },
  { name: "Guzzlord", type: [PokemonTypes.dark, PokemonTypes.dragon] },
  { name: "Necrozma", type: [PokemonTypes.psychic] },
  { name: "Magearna", type: [PokemonTypes.steel] },
  { name: "Marshadow", type: [PokemonTypes.fighting, PokemonTypes.ghost] },
  { name: "Poipole", type: [PokemonTypes.poison] },
  { name: "Naganadel", type: [PokemonTypes.poison, PokemonTypes.dragon] },
  { name: "Stakataka", type: [PokemonTypes.rock, PokemonTypes.steel] },
  { name: "Blacephalon", type: [PokemonTypes.fire, PokemonTypes.ghost] },
  { name: "Zeraora", type: [PokemonTypes.electric] },
  { name: "Meltan", type: [PokemonTypes.steel] },
  { name: "Melmetal", type: [PokemonTypes.steel] },
];
